"""add monitoring job entity

Revision ID: 21100fbd828d
Revises: c5404c0fec28
Create Date: 2025-12-06 10:23:39.805765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21100fbd828d'
down_revision: Union[str, Sequence[str], None] = 'c5404c0fec28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'EXECUTING', 'COMPLETED', 'FAILED', name='jobstatus').create(op.get_bind())
    op.create_table('monitoringjob',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING','SCHEDULED' , 'EXECUTING', 'COMPLETED', 'FAILED', name='jobstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_monitoringjob_booking_id'), 'monitoringjob', ['booking_id'], unique=False)
    op.create_index(op.f('ix_monitoringjob_job_id'), 'monitoringjob', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoringjob_job_id'), table_name='monitoringjob')
    op.drop_index(op.f('ix_monitoringjob_booking_id'), table_name='monitoringjob')
    op.drop_table('monitoringjob')
    sa.Enum('PENDING', 'SCHEDULED', 'EXECUTING', 'COMPLETED', 'FAILED', name='jobstatus').drop(op.get_bind())
    # ### end Alembic commands ###
