"""add desk_id to monitoring job

Revision ID: c98ce377ce20
Revises: 21100fbd828d
Create Date: 2025-12-07 13:22:39.520737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c98ce377ce20'
down_revision: Union[str, Sequence[str], None] = '21100fbd828d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoringjob', sa.Column('desk_id', sa.BigInteger(), nullable=False))
    op.alter_column('monitoringjob', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('monitoringjob', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('monitoringjob', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_monitoringjob_desk_id'), 'monitoringjob', ['desk_id'], unique=False)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='jobstatus',
        new_values=['PENDING', 'SCHEDULED', 'EXECUTING', 'COMPLETED', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='monitoringjob', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='jobstatus',
        new_values=['PENDING', 'EXECUTING', 'COMPLETED', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='monitoringjob', column_name='status')],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f('ix_monitoringjob_desk_id'), table_name='monitoringjob')
    op.alter_column('monitoringjob', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('monitoringjob', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('monitoringjob', 'scheduled_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('monitoringjob', 'desk_id')
    # ### end Alembic commands ###
