"""enforce desk_id on desk entity

Revision ID: 4456299c5fc7
Revises: b1cc0d8a0c7a
Create Date: 2025-12-03 14:18:16.338184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4456299c5fc7'
down_revision: Union[str, Sequence[str], None] = 'b1cc0d8a0c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
