"""Update desk model to passively delete all related data

Revision ID: 6a53b0c8c681
Revises: fe78d84cc575
Create Date: 2025-11-24 07:26:01.523316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a53b0c8c681'
down_revision: Union[str, Sequence[str], None] = 'fe78d84cc575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
