"""Add orientation and remove unnecessary fields

Revision ID: b1cc0d8a0c7a
Revises: c3d4e5f6a7b8
Create Date: 2025-12-03 14:01:13.793633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1cc0d8a0c7a'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_desk_config_desk_id'), table_name='desk_config')
    op.create_index(op.f('ix_desk_config_desk_id'), 'desk_config', ['desk_id'], unique=False)
    op.drop_column('desk_errors', 'error_message')
    op.drop_index(op.f('ix_desk_state_desk_id'), table_name='desk_state')
    op.create_index(op.f('ix_desk_state_desk_id'), 'desk_state', ['desk_id'], unique=False)
    op.drop_index(op.f('ix_desk_usage_desk_id'), table_name='desk_usage')
    op.add_column('desks', sa.Column('orientation', sa.String(), nullable=True))
    op.add_column('desks', sa.Column('pos_x', sa.Float(), nullable=True))
    op.add_column('desks', sa.Column('pos_y', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_desks_name'), table_name='desks')
    op.create_index(op.f('ix_desks_id'), 'desks', ['id'], unique=False)
    op.drop_column('desks', 'y')
    op.drop_column('desks', 'location')
    op.drop_column('desks', 'name')
    op.drop_column('desks', 'x')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('desks', sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('desks', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('desks', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('desks', sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_desks_id'), table_name='desks')
    op.create_index(op.f('ix_desks_name'), 'desks', ['name'], unique=True)
    op.drop_column('desks', 'pos_y')
    op.drop_column('desks', 'pos_x')
    op.drop_column('desks', 'orientation')
    op.create_index(op.f('ix_desk_usage_desk_id'), 'desk_usage', ['desk_id'], unique=True)
    op.drop_index(op.f('ix_desk_state_desk_id'), table_name='desk_state')
    op.create_index(op.f('ix_desk_state_desk_id'), 'desk_state', ['desk_id'], unique=True)
    op.add_column('desk_errors', sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_desk_config_desk_id'), table_name='desk_config')
    op.create_index(op.f('ix_desk_config_desk_id'), 'desk_config', ['desk_id'], unique=True)
    # ### end Alembic commands ###
