"""Add cascade deletes to desk foreign keys

Revision ID: cd89fb96d882
Revises: 6a53b0c8c681
Create Date: 2025-11-24 07:47:51.347294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd89fb96d882'
down_revision: Union[str, Sequence[str], None] = '6a53b0c8c681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('desk_config_desk_id_fkey'), 'desk_config', type_='foreignkey')
    op.create_foreign_key(None, 'desk_config', 'desks', ['desk_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('desk_errors_desk_id_fkey'), 'desk_errors', type_='foreignkey')
    op.create_foreign_key(None, 'desk_errors', 'desks', ['desk_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('desk_state_desk_id_fkey'), 'desk_state', type_='foreignkey')
    op.create_foreign_key(None, 'desk_state', 'desks', ['desk_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('desk_usage_desk_id_fkey'), 'desk_usage', type_='foreignkey')
    op.create_foreign_key(None, 'desk_usage', 'desks', ['desk_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'desk_usage', type_='foreignkey')
    op.create_foreign_key(op.f('desk_usage_desk_id_fkey'), 'desk_usage', 'desks', ['desk_id'], ['id'])
    op.drop_constraint(None, 'desk_state', type_='foreignkey')
    op.create_foreign_key(op.f('desk_state_desk_id_fkey'), 'desk_state', 'desks', ['desk_id'], ['id'])
    op.drop_constraint(None, 'desk_errors', type_='foreignkey')
    op.create_foreign_key(op.f('desk_errors_desk_id_fkey'), 'desk_errors', 'desks', ['desk_id'], ['id'])
    op.drop_constraint(None, 'desk_config', type_='foreignkey')
    op.create_foreign_key(op.f('desk_config_desk_id_fkey'), 'desk_config', 'desks', ['desk_id'], ['id'])
    # ### end Alembic commands ###
