"""create new desk tables

Revision ID: fe78d84cc575
Revises: 
Create Date: 2025-11-16 13:10:26.080559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe78d84cc575'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desks_name'), 'desks', ['name'], unique=True)
    op.create_table('desk_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desk_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['desk_id'], ['desks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desk_config_desk_id'), 'desk_config', ['desk_id'], unique=True)
    op.create_table('desk_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desk_id', sa.Integer(), nullable=False),
    sa.Column('time_s', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['desk_id'], ['desks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desk_errors_desk_id'), 'desk_errors', ['desk_id'], unique=False)
    op.create_table('desk_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desk_id', sa.Integer(), nullable=False),
    sa.Column('position_mm', sa.Integer(), nullable=True),
    sa.Column('speed_mms', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_position_lost', sa.Boolean(), nullable=False),
    sa.Column('is_overload_protection_up', sa.Boolean(), nullable=False),
    sa.Column('is_overload_protection_down', sa.Boolean(), nullable=False),
    sa.Column('is_anti_collision', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['desk_id'], ['desks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desk_state_desk_id'), 'desk_state', ['desk_id'], unique=True)
    op.create_table('desk_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desk_id', sa.Integer(), nullable=False),
    sa.Column('activations_counter', sa.Integer(), nullable=False),
    sa.Column('sit_stand_counter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['desk_id'], ['desks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desk_usage_desk_id'), 'desk_usage', ['desk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_desk_usage_desk_id'), table_name='desk_usage')
    op.drop_table('desk_usage')
    op.drop_index(op.f('ix_desk_state_desk_id'), table_name='desk_state')
    op.drop_table('desk_state')
    op.drop_index(op.f('ix_desk_errors_desk_id'), table_name='desk_errors')
    op.drop_table('desk_errors')
    op.drop_index(op.f('ix_desk_config_desk_id'), table_name='desk_config')
    op.drop_table('desk_config')
    op.drop_index(op.f('ix_desks_name'), table_name='desks')
    op.drop_table('desks')
    # ### end Alembic commands ###
