"""new table with tz

Revision ID: 781bd8e126f9
Revises: 8fa4542e39fc
Create Date: 2025-11-13 14:39:48.260274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781bd8e126f9'
down_revision: Union[str, Sequence[str], None] = '8fa4542e39fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occupancyrecord_timestamp'), table_name='occupancyrecord')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_occupancyrecord_timestamp'), 'occupancyrecord', ['timestamp'], unique=False)
    # ### end Alembic commands ###
