"""new changes

Revision ID: 7d58ebd53a98
Revises: 80afe3241d24
Create Date: 2025-11-14 07:43:48.191106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d58ebd53a98'
down_revision: Union[str, Sequence[str], None] = '80afe3241d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_occupancyrecord_timestamp'), 'occupancyrecord', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occupancyrecord_timestamp'), table_name='occupancyrecord')
    # ### end Alembic commands ###
