"""Update table with preferred user heights

Revision ID: 8f3a63f136f3
Revises: a92c5dc74ccd
Create Date: 2025-12-02 16:40:44.631036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f3a63f136f3'
down_revision: Union[str, Sequence[str], None] = 'a92c5dc74ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('user', sa.Column('preferred_standing_height_cm', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('preferred_sitting_height_cm', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('user_height_cm', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.drop_column('user', 'username')
    op.drop_column('user', 'id')
    op.drop_column('user', 'role')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'email')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_column('user', 'user_height_cm')
    op.drop_column('user', 'preferred_sitting_height_cm')
    op.drop_column('user', 'preferred_standing_height_cm')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
